// Generated by scripts/generate_syscall.py
include!(concat!(env!("OUT_DIR"), "/syscall_consts_x64_generated.rs"));

// Generated by scripts/generate_syscall.py
include!(concat!(
    env!("OUT_DIR"),
    "/syscall_name_arch_x64_generated.rs"
));
